### ISSUE TITLE
Does there exist a gearmenu for 3.35 wlk client

### ISSUE THREAD

**Issue by Miphalolx** [RagedUnicorn/wow-wotlkc-gearmenu#1]
Recently ppl run a ps for old wlk 3.35 client ,and can not find a version can support this.
does there exist a gearmenu support that version client?

**Comment by RagedUnicorn** [comment]
Hi @Miphalolx,

Unfortunately not. I only played 1.12.1 on private servers and started to develop the first version during that time. There is one for official wotlk classic servers though but the api for that version is vastly different from the one used for private server.

Cheers,
RagedUnicorn
